---
# Global variables used across the playbooks
# Edit this file when sure of the values.

#EAP Ports
jboss_http_port: 8080                 # Http port
jboss_https_port: 8443                # Https port

# EAP VAULT
eap_root: /opt/apps/rhpam
artifacts_dir: "{{ eap_root }}/artifacts"
eap_home: "{{ eap_root }}/jboss-eap-7.4"
eap_ver: jboss-eap-7.4
eap_vault_path: "{{ eap_home }}/vault"
eap_vault_key_file: "{{ eap_home }}/vault/vault.keystore"
eap_vault_storepass: panther@123 # password that is used to authenticate to the keystore so that the key can be read.The password must be at least 6 characters long
eap_vault_keypass: "{{ eap_vault_storepass }}"
eap_vault_init_password: s0mepassw0rd! # Security Attribute (SEC-ATTR) - The password which is being stored in the password vault. Used to initialize the vault
eap_vault_salt: 12345678 # The salt value is a random string of eight characters used, together with the iteration count, to encrypt the content of the keystore.Salt has to be exactly 8 characters long
eap_vault_alias: vault # The alias of the entry encapsulated in the keystore. Comes in handy to edit when testing to avoid Duplicate resource [(\\\"core-service\\\" => \\\"vault\\\")] error


#EAP Admin credentials
eap_admin_user: eapAdmin
eap_admin_pwd: Admin@123

# ++ SERVICE USER +++
eap_svc_user: jboss  # Service User within the RHEL system.


# ++ BUSINESS CENTRAL VARIABLES+++

business_central_zip: rhpam-7.13.0-business-central-eap7-deployable.zip
business_central_temp: /tmp/bc
business_central_data: "{{ eap_root }}/data"
business_central_admin_usr: dadmin # Client to provide
business_central_admin_pwd: dadmin # Passwords to come from Hashivault
maven_enterprise_repo_url: https://maven.repository.redhat.com/ga/
business_central_controller_usr: kie
business_central_controller_pwd: kie1234


# +++ MAVEN +++ 
maven_data_directory: "{{ eap_root }}/data"
maven_settings_xml_path: "{{ maven_data_directory }}/settings.xml"