---
# Global variables used across the playbooks
# Edit this file when sure of the values.

#EAP Ports
jboss_http_port: 8080                 # Http port
jboss_https_port: 8443                # Https port

# EAP VAULT
eap_root: /opt/apps/rhpam
artifacts_dir: "{{ eap_root }}/artifacts"
eap_home: "{{ eap_root }}/jboss-eap-7.4"
eap_ver: jboss-eap-7.4
eap_vault_path: "{{ eap_home }}/vault"
eap_vault_key_file: "{{ eap_home }}/vault/vault.keystore"
eap_vault_alias: vault # The alias of the entry encapsulated in the keystore. Comes in handy to edit when testing to avoid Duplicate resource [(\\\"core-service\\\" => \\\"vault\\\")] error




# ++ SERVICE USER +++
eap_svc_user: jboss  # Service User within the RHEL system.


# ++ BUSINESS CENTRAL VARIABLES+++

business_central_zip: rhpam-7.13.0-business-central-eap7-deployable.zip
business_central_temp: /tmp/bc
business_central_data: "{{ eap_root }}/data"
maven_enterprise_repo_url: https://maven.repository.redhat.com/ga/
business_central_address:  ip-10-0-158-133.us-west-2.compute.internal


# +++ MAVEN +++ 
maven_data_directory: "{{ eap_root }}/data"
maven_settings_xml_path: "{{ maven_data_directory }}/settings.xml"


# +++ KIE SERVER +++++
kie_server_address: ip-10-0-157-227.us-west-2.compute.internal
kie_server_zip: rhpam-7.13.0-kie-server-ee8.zip
kie_server_temp: /tmp/kie
kie_server_admin_user: kie
kie_server_admin_pwd: kie1234



# AURORA DB
db_host: pam-sandbox.cluster-clmjgu4bbu2f.us-west-2.rds.amazonaws.com
db_host_port: 5432
db_name: dev_test_db
rhpam_add_on: rhpam-7.13.0-add-ons.zip
kie_server_persistent_dialect: "org.hibernate.dialect.PostgreSQLDialect"
migration_zip: rhpam-7.13.0-migration-tool.zip
postgred_jbm_schema: "{{ kie_server_temp }}/rhpam-7.13.0-migration-tool/ddl-scripts/postgresql/postgresql-jbpm-schema.sql"


