---
# To be in a vault.
# Now stored as environmental variables

# +++ EAP VAULT

# Password that is used to AUTHENTICATE TO THE KEYSTORE so that the key can be read. The password must be at least 6 characters long.
eap_vault_storepass: "{{ lookup('env','EAP_VAULT_STOREPASS') }}"
eap_vault_keypass: "{{ eap_vault_storepass }}"

eap_vault_init_password: "{{ lookup('env','EAP_VAULT_INIT_PWD') }}" # Security Attribute (SEC-ATTR) - The password which is being stored in the password vault. Used to initialize the vault
eap_vault_salt: "{{ lookup('env','EAP_VAULT_SALT') }}" # The salt value is a random string of eight characters used, together with the iteration count, to encrypt the content of the keystore.Salt has to be exactly 8 characters long


# +++EAP Admin credentials ++

eap_admin_user: "{{ lookup('env','EAP_ADMIN_USER') }}"
eap_admin_pwd: "{{ lookup('env','EAP_ADMIN_PASS') }}"

# ++Busines Central +++
business_central_admin_usr: "{{ lookup('env','BC_ADMIN_USER') }}" # Client to provide
business_central_admin_pwd: "{{ lookup('env','BC_ADMIN_PASS') }}" # Passwords to come from Hashivault
business_central_controller_usr: "{{ business_central_admin_usr }}"
business_central_controller_pwd: "{{ business_central_admin_pwd }}"

# ++ AURORA DB
db_master_username : "{{ lookup('env','AURORA_MASTER_USER') }}"
db_master_password : "{{ lookup('env','AURORA_MASTER_PASS') }}"

# ++ KIE CREDENTIALS
kie_server_admin_user: "{{ business_central_controller_usr }}"
kie_server_admin_pwd: "{{ business_central_controller_pwd }}"
