---
# Main tasks
# - name: main - Install - Stop RHEL services
#   command: "sudo systemctl stop jboss-eap"

# - import_tasks: install.yml

# - name: main - Start RHEL Service
#   command: "sudo systemctl start jboss-eap"

# - import_tasks: users.yml

# - import_tasks: setup.yml

- import_tasks: datasource.yml # Need a smarter way to write the .xml file than copying whole of it.

- import_tasks: vault.yml # Should always come last.

- import_tasks: testing.yml

