# Dynamic variables for kie server
org_kie_server_repo: "${jboss.server.data.dir}"
org_kie_example: "true"
org_jbpm_designer_perspective: "full"
designerdataobjects: "false"
org_kie_server_user: "{{ kie_server_admin_user }}"
org_kie_server_pwd: "{{ kie_server_admin_pwd }}"
org_kie_server_location: "http://localhost:8080/kie-server/services/rest/server"
org_kie_server_controller: "http://{{ business_central_address }}:8080/business-central/rest/controller"
org_kie_server_controller_user: "{{ kie_server_admin_user }}"
org_kie_server_controller_pwd: "{{ kie_server_admin_pwd }}"
org_kie_server_id: "{{ kie_server_address }}"


org_kie_server_persistence_ds: "{{ db_host }}"
org_kie_server_persistence_dialect: "{{ kie_server_persistent_dialect }}"